---
title: "02_Eye_Morphology_Literature"
author: "Conrad Alting"
date: "2023-06-11"
output:
  html_document:
    df_print: paged
always_allow_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
####
# This script imports and aggregates publicly available data on human eye 
# morphology provided by Danel et al. (2023).
# Data found in Tab. 1 Danel et al. (2020) will be manually imported


# 1. Library import -------------------------------------------------------
library(knitr)
options(kableExtra.auto_format = FALSE)
library(tidyverse)
library(kableExtra)


```


```{r include=TRUE}
# 2. Data import (Danel et al. 2023) --------------------------------------

# Data can be found in S1 and S2 under:
# https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0284079#sec013

df_avg <- read.csv("C:/Users/calti/Documents/Masterarbeit/Data/Data Experiment 1 (Eye Morphology)/Eye_Measurements_avg_mm.csv")

ext_csv_path <- "C:\\Users\\calti\\Documents\\Masterarbeit\\Data\\External Data"
ext_csv_files <-  list.files(ext_csv_path)

for(i in seq(1:length(ext_csv_files))){
  file_path <- paste(ext_csv_path, ext_csv_files[i], sep="\\")
  if(i == 1){
    df <- read.csv(file_path, stringsAsFactors = T)
    df <- df %>%
      select(Photo_id,SSI,RIL,WHR,Photo_Sex)
  }else{
    tmp <- read.csv(file_path, stringsAsFactors = T)
    tmp <- tmp %>%
      select(Photo_id,SSI,RIL,WHR,Photo_Sex)
    
    df <- rbind(df, tmp)
  }
}

# recode Photo_Sex column (during import F gets converted to bool/FALSE)
df$Photo_Sex <- ifelse(df$Photo_Sex==FALSE, "f", "m")

# number of unique subjects
length(unique(df$Photo_id))

# number of rows in df
nrow(df)

# there are 30 rows per photo. We only want to keep unique rows 
# (= 1 row per photo)
df_unique <- df %>%
  distinct()

# check number of unique subjects/photo ids
length(unique(df_unique$Photo_id))



# 2.1. Data Summary (Danel et al. 2023) -----------------------------------


df_danel_2023 <- df_unique %>%
  group_by(Photo_Sex) %>%
  summarise(
    SSI_M = mean(SSI),
    SSI_Md = median(SSI),
    SSI_SD = sd(SSI),
    WHR_M = mean(WHR),
    WHR_Md = median(WHR),
    WHR_SD = sd(WHR),
    RIL_M = mean(RIL),
    RIL_Md = median(RIL),
    RIL_SD = sd(RIL)
  )

colnames(df_danel_2023)[1] <- "looker_gender"
df_danel_2023

# 3. Data import (Danel et al., 2020) -------------------------------------

df_danel_2020 <- tibble(
  looker_gender = c("f", "m"),
  SSI_M = c(1.85, 1.91),
  SSI_Md = c(1.84, 1.91),
  SSI_Min = c(1.67, 1.68),
  SSI_Max = c(2.1, 2.13),
  SSI_SD = c(0.095, 0.1),
  SSI_Normality = c("W=0.9859, p=0.81", "W=0.9863, p=0.83"),
  WHR_M = c(2.65, 2.85),
  WHR_Md = c(2.64, 2.80),
  WHR_Min = c(2.19, 2.18),
  WHR_Max = c(3.18, 3.83),
  WHR_SD = c(0.258, 0.315),
  WHR_Normality = c("W=0.9744, p=0.35", "W=0.9662, p=0.16"),
  RIL_M = c(37.78, 33.85),
  RIL_Md = c(38.88, 34.74),
  RIL_Min = c(16.86, 16.62),
  RIL_Max = c(54.23, 52.37),
  RIL_SD = c(7.30, 9.017),
  RIL_Normality = c("W=0.9725, p=0.29", "W=0.9747, p=0.36"),
  SSR_M = c(42.36, 43.52),
  SSR_Md = c(41.71, 42.92),
  SSR_Min = c(29.59, 30.80),
  SSR_Max = c(60.80, 54.57),
  SSR_SD = c(6.92, 5.642),
  SSR_Normality = c("W=0.9781, p=0.47", "W=0.9738, P=0.33")
)

df_danel_2020 <- tibble(
  looker_gender = c("f", "m"),
  SSI_M = c(1.85, 1.91),
  SSI_Md = c(1.84, 1.91),
  SSI_Min = c(1.67, 1.68),
  SSI_Max = c(2.1, 2.13),
  SSI_SD = c(0.095, 0.1),
  SSI_Normality = c("W = 0.9859, p = 0.81", "W = 0.9863, p = 0.83"),
  WHR_M = c(2.65, 2.85),
  WHR_Md = c(2.64, 2.80),
  WHR_Min = c(2.19, 2.18),
  WHR_Max = c(3.18, 3.83),
  WHR_SD = c(0.258, 0.315),
  WHR_Normality = c("W = 0.9744, p = 0.35", "W = 0.9662, p = 0.16"),
  RIL_M = c(37.78, 33.85),
  RIL_Md = c(38.88, 34.74),
  RIL_Min = c(16.86, 16.62),
  RIL_Max = c(54.23, 52.37),
  RIL_SD = c(7.30, 9.017),
  RIL_Normality = c("W = 0.9725, p = 0.29", "W = 0.9747, p = 0.36"),
  SSR_M = c(42.36, 43.52),
  SSR_Md = c(41.71, 42.92),
  SSR_Min = c(29.59, 30.80),
  SSR_Max = c(60.80, 54.57),
  SSR_SD = c(6.92, 5.642),
  SSR_Normality = c("W = 0.9781, p = 0.47", "W = 0.9738, p = 0.33")
)


df_danel_2020



# 4. Authors data ---------------------------------------------------------

df_author <- df_avg %>%
  group_by(looker_gender) %>%
  summarise(
    SSI_M = mean(ssi_alt_mm),
    SSI_Md = median(ssi_alt_mm),
    SSI_SD = sd(ssi_alt_mm),
    WHR_M = mean(whr_mm),
    WHR_Md = median(whr_mm),
    WHD_SD = sd(whr_mm),
    RIL_M = mean(ril),
    RIL_Md = median(ril),
    RIL_SD = sd(ril),
    SSR_M = mean(ssr),
    SSR_Md = median(ssr),
    SSR_SD = sd(ssr)
  )

df_author <- df_avg %>%
  group_by(looker_gender) %>%
  summarise(
    SSI_M = mean(ssi_mm),
    SSI_Md = median(ssi_mm),
    SSI_SD = sd(ssi_mm),
    WHR_M = mean(whr_mm),
    WHR_Md = median(whr_mm),
    WHR_SD = sd(whr_mm),
    RIL_M = mean(ril),
    RIL_Md = median(ril),
    RIL_SD = sd(ril),
    SSR_M = mean(ssr),
    SSR_Md = median(ssr),
    SSR_SD = sd(ssr)
  )

df_author <- df_avg %>%
  group_by(looker_gender) %>%
  summarise(
    SSI_M = mean(ssi_mm),
    SSI_Md = median(ssi_mm),
    SSI_Min = min(ssi_mm),
    SSI_Max = max(ssi_mm),
    SSI_SD = sd(ssi_mm),
    SSI_Normality = paste("W =", round(shapiro.test(df_avg$ssi_mm)$statistic[[1]], 3), "p=", round(shapiro.test(df_avg$ssi_mm)$p.value, 3), sep=" "),
    WHR_M = mean(whr_mm),
    WHR_Md = median(whr_mm),
    WHR_Min = min(whr_mm),
    WHR_Max = max(whr_mm),
    WHR_SD = sd(whr_mm),
    WHR_Normality = paste("W =", round(shapiro.test(df_avg$whr_mm)$statistic[[1]], 3), "p =", round(shapiro.test(df_avg$whr_mm)$p.value, 3), sep=" "),
    RIL_M = mean(ril),
    RIL_Md = median(ril),
    RIL_Min = min(ril),
    RIL_Max = max(ril),
    RIL_SD = sd(ril),
    RIL_Normality = paste("W =", round(shapiro.test(df_avg$ril)$statistic[[1]], 3), "p =", round(shapiro.test(df_avg$ril)$p.value, 3), sep=" "),
    SSR_M = mean(ssr),
    SSR_Md = median(ssr),
    SSR_Min = min(ssr),
    SSR_Max = max(ssr),
    SSR_SD = sd(ssr),
    SSR_Normality = paste("W =", round(shapiro.test(df_avg$ssr)$statistic[[1]], 3), "p =", round(shapiro.test(df_avg$ssr)$p.value, 3), sep=" "),
  )


# add study authors
df_danel_2020$study <- "Danel et al., 2023"
df_danel_2020

df_author$study <- "Eigene Stichprobe"
df_author



# 5. Combined Data --------------------------------------------------------

# combine own sample statistics and danel et al.'s data
(df_comp <- rbind(df_author, df_danel_2020))

df_comp2 <- df_comp %>%
  pivot_longer(!contains(c("looker_gender", "study"), ignore.case=FALSE),
               names_to = c("Parameter", ".value"),
               names_sep = "\\_")
df_comp2


df_comp3 <- df_comp2 %>%
  pivot_longer(c("M", "Md", "SD"),
               names_to = c("Measures"),
               values_to = c("Values"))
df_comp3


#-------------------------

# pivot own data to long format (one column with parameter names)
df_auth1 <- df_author %>%
  select(-study) %>%
  pivot_longer(!contains(c("looker_gender"), ignore.case=FALSE),
               names_to = c("Parameter", ".value"),
               names_sep = "\\_")

# pivot Danel data to long format (one column with parameter names)
df_danel1 <- df_danel_2020 %>%
  select(-study) %>%
  pivot_longer(!contains(c("looker_gender"), ignore.case=FALSE),
               names_to = c("Parameter", ".value"),
               names_sep = "\\_")  

# create separate df for male and female data (own and Danel study)
df_auth_m <- df_auth1 %>%
  filter(looker_gender=="m") %>%
  select(-looker_gender)
df_auth_f <- df_auth1 %>%
    filter(looker_gender=="f") %>%
    select(M, Md, SD)

df_danel_m <- df_danel1 %>%
    filter(looker_gender=="m") %>%
    select(M, Md, SD)
df_danel_f <- df_danel1 %>%
    filter(looker_gender=="f") %>%
    select(M, Md, SD)


# get number of male and female observers
df_avg %>%
  group_by(looker_gender) %>%
  summarise(
    n = n()
  )

# create kable table 
# kbl(cbind(df_auth_m, df_auth_f, df_danel_m, df_danel_f), format="html", 
#     digits=2, 
#     escape=F,
#     font_size = 11) %>%
#   add_header_above(c(" " = 1, "Männer ($n=14$)" = 3, "Frauen ($n=26$)" = 3, "Männer ($n=50%)" = 3, "Frauen ($n=50$)" = 3)) %>%
#   add_header_above(c(" "=1, "Eigene Studie ($n=40$)" = 6, "Danel et al., 2020 ($n=100$)" = 6), align="l") %>%
#   
#   kable_classic(full_width = T, html_font = "Times New Roman")
  


df_auth_mm <- df_auth1 %>%
    filter(looker_gender=="m") %>%
    select(-looker_gender)
df_auth_ff <- df_auth1 %>%
    filter(looker_gender=="f") %>%
    select(M, Md, SD)

df_danel_mm <- df_danel1 %>%
    filter(looker_gender=="m") %>%
    select(-looker_gender)
df_danel_ff <- df_danel1 %>%
    filter(looker_gender=="f") %>%
    select(M, Md, SD)


# tbl1 <- kbl(rbind(cbind(df_auth_mm, df_auth_ff), cbind(df_danel_mm, df_danel_ff)), 
#     format="html", 
#     digits=2, 
#     escape=F,
#     font_size = 8,
#     col.names = c(" ", "M", "Md", "SD", "M", "Md", "SD"),
#     caption = "Tab. 1 Deskriptive Statistiken für Messungen der Photos",
#     table.attr = "style='width:100%;'") %>%
#   add_header_above(c(" " = 1, "Männer ($n=14$)" = 3, "Frauen ($n=26$)" = 3)) %>%
#   pack_rows("Eigene Daten", 1, 4) %>%
#   pack_rows("Danel et al. (2023)", 5, 8) %>%
#   kable_classic(html_font = "Times New Roman") %>%
#   footnote("$M$ Mittelwert, $Md$ Median, $SD$ Standardabweichung", general_title = "")
# 
# tbl1


# df with normality and range data
df_auth_mm <- df_auth1 %>%
  filter(looker_gender=="m") %>%
  select(-looker_gender)
df_auth_ff <- df_auth1 %>%
  filter(looker_gender=="f") %>%
  select(M, Md, Min, Max, SD, Normality)

df_danel_mm <- df_danel1 %>%
  filter(looker_gender=="m") %>%
  select(-looker_gender)
df_danel_ff <- df_danel1 %>%
  filter(looker_gender=="f") %>%
  select(M, Md, Min, Max, SD, Normality)


kbl(rbind(cbind(df_auth_mm, df_auth_ff), cbind(df_danel_mm, df_danel_ff)), 
    format="html", 
    digits=2, 
    escape=F,
    font_size = 6,
    col.names = c(" ", "M", "Md", "Min", "Max", "SD", "Normality", "M", "Md", "Min", "Max", "SD", "Normality"),
    caption = "Tab. 1 Deskriptive Statistiken für Messungen der Photos",
    table.attr = "style='width:100%;'") %>%
  add_header_above(c(" " = 1, "Männer ($n=14$)" = 6, "Frauen ($n=26$)" = 6)) %>%
  pack_rows("Eigene Daten", 1, 4) %>%
  pack_rows("Danel et al. (2023)", 5, 8) %>%
  kable_classic(html_font = "Times New Roman") %>%
  footnote("$M$ Mittelwert, $Md$ Median, $Min/Max$ minimaler/maximaler Wert, $SD$ Standardabweichung, $Normality$ Ergebnis des Shapiro-Wilk-Testes auf Normalverteilung", 
           general_title = "",
           threeparttable = T,
           fixed_small_size=T)

```

